export const projects = [
  {
    title: 'Youtube Clone',
    description: "Using ReactJS, Tailwind CSS, Redux, and Rapid API , I have created this Youtube Clone where we can visit the videos from the Youtube API available on Rapid API.Tailwind CSS is used to style the website, Redux is used for server side management.",
    image: '/images/1.png',
    tags: ['ReactJS', 'Tailwind', 'Redux', 'Rapid-API', 'Front-End'],
    source: 'https://github.com',
    visit: 'https://vercel.com',
    id: 0,
  },
  {
    title: 'WebThree Business Website ',
    description: "This is typical front-end website which fulfills the need of the customer for a attractive landing page which automatically attracts the users. The website uses ReactJS as framework, Tailwind CSS for styling.",
    image: '/images/2.png',
    tags: ['React', 'Tailwind', 'Front-End'],
    source: 'https://github.com',
    visit: 'https://vercel.com',
    id: 1,
  },
  {
    title: 'E-Commerce',
    description: "This is an E-Commerce website which is build upon modern day technology for front-end and back-end which are NextJS and Sanity for all-round database service.Stripe is used for payment service.",
    image: '/images/2.png',
    tags: ['Nextjs', 'Sanity', 'Stripe', 'Front-End'],
    source: 'https://github.com',
    visit: 'https://vercel.com',
    id: 1,
  },
  {
    title: 'Banking Landing Page',
    description: "This website is made by keeping in mind the importance of modern banking.As major factor of business website is used to attract modern day users, it does that emphatically. The website uses ReactJS as framework, Tailwind CSS for styling.",
    image: '/images/2.png',
    tags: ['React', 'Tailwind', 'Front-End'],
    source: 'https://github.com',
    visit: 'https://vercel.com',
    id: 1,
  },
  {
    title: 'Spotify Clone',
    description: "This is Spotify Music Player type web application which uses 'Shazam API' to fetch songs and set according to the users.The website uses modern tech such as ReactJS, TailwindCSS, Redux, Rapid API",
    image: '/images/3.jpg',
    tags: ['ReactJS', 'Tailwind', 'Redux', 'Rapid-API', 'Front-End'],
    source: 'https://github.com',
    visit: 'https://vercel.com',
    id: 2,
  },
  {
    title: 'Blockchain Crowdfunding App',
    description: "This is a web3 crowdfunding app which caters modern day technologies.The tech that has been used is React JS, Tailwind CSS.But main thing that makes this website is the use of 'thirdweb'.",
    image: '/images/4.jpg',
    tags: ['React JS', 'thirdweb', 'web3', 'Front-End'],
    source: 'https://github.com',
    visit: 'https://vercel.com',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2021, text: 'Started my journey', },
  { year: 2021, text: 'Started continuously contributing to project', },
  { year: 2022, text: 'Started making projects on various topics and fields.', },
  { year: 2022, text: 'Completed 500 problems on Leetcode and 300 problems on GFG', },
  { year: 2023, text: 'Contributing to Open Source Projects and participating in Hackathons', },
  { year: 2023, text: 'Started learning Machine Learning and Web3 :)', },
];